# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/alien/ue5
GAMEPROJECTFILE =/home/alien/Documents/Unreal Projects/Cypocitytd/Cypocitytd.uproject

TARGETS = \
	Cypocitytd-Linux-DebugGame  \
	Cypocitytd-Linux-Shipping  \
	Cypocitytd \
	CypocitytdEditor-Linux-DebugGame  \
	CypocitytdEditor-Linux-Shipping  \
	CypocitytdEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend CypocitytdEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug CypocitytdEditor-Linux-Debug


Cypocitytd-Linux-DebugGame:
	 $(PROJECTBUILD) Cypocitytd Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Cypocitytd-Linux-Shipping:
	 $(PROJECTBUILD) Cypocitytd Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Cypocitytd:
	 $(PROJECTBUILD) Cypocitytd Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

CypocitytdEditor-Linux-DebugGame:
	 $(PROJECTBUILD) CypocitytdEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

CypocitytdEditor-Linux-Shipping:
	 $(PROJECTBUILD) CypocitytdEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

CypocitytdEditor:
	 $(PROJECTBUILD) CypocitytdEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
